#!/usr/bin/env node
/**
 * This script reads the built widget HTML file and inlines all CSS and JS,
 * creating a self-contained HTML file that can be served by the worker.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');
const ASSETS_DIR = path.resolve(ROOT_DIR, 'assets');
const OUTPUT_DIR = path.resolve(ROOT_DIR, 'src', 'server');

function embedWidget() {
  const htmlPath = path.join(ASSETS_DIR, 'src', 'components', 'booking-search-results.html');
  
  if (!fs.existsSync(htmlPath)) {
    console.error('❌ Widget HTML not found. Run "npm run build" first.');
    process.exit(1);
  }

  let htmlContent = fs.readFileSync(htmlPath, 'utf8');
  
  // Find all CSS links and inline them
  const cssRegex = /<link[^>]*href="\/([^"]+\.css)"[^>]*>/g;
  let match;
  while ((match = cssRegex.exec(htmlContent)) !== null) {
    const cssFile = match[1];
    const cssPath = path.join(ASSETS_DIR, cssFile);
    if (fs.existsSync(cssPath)) {
      const cssContent = fs.readFileSync(cssPath, 'utf8');
      htmlContent = htmlContent.replace(match[0], `<style>${cssContent}</style>`);
      console.log(`✅ Inlined CSS: ${cssFile}`);
    }
  }
  
  // Find all JS script tags and inline them, including their dependencies
  const jsRegex = /<script[^>]*src="\/([^"]+\.js)"[^>]*><\/script>/g;
  const jsFiles = [];
  while ((match = jsRegex.exec(htmlContent)) !== null) {
    jsFiles.push(match[1]);
  }
  
  // Read entry JS file and extract chunk imports
  let combinedJs = '';
  const processedFiles = new Set();
  
  function processJsFile(jsFile) {
    if (processedFiles.has(jsFile)) return;
    processedFiles.add(jsFile);
    
    const jsPath = path.join(ASSETS_DIR, jsFile);
    if (!fs.existsSync(jsPath)) {
      console.warn(`⚠️  JS file not found: ${jsFile}`);
      return;
    }
    
    let jsContent = fs.readFileSync(jsPath, 'utf8');
    console.log(`✅ Inlined JS: ${jsFile}`);
    
    // Find imports in the JS file (looking for "./chunk-hash.js" patterns)
    const importRegex = /from\s*["']\.\/([^"']+\.js)["']/g;
    let importMatch;
    const imports = [];
    while ((importMatch = importRegex.exec(jsContent)) !== null) {
      imports.push(importMatch[1]);
    }
    
    // Process imported chunks first
    for (const importFile of imports) {
      processJsFile(importFile);
    }
    
    // Remove import statements since we're inlining everything
    jsContent = jsContent.replace(/import\s*\{[^}]*\}\s*from\s*["'][^"']+["'];?/g, '');
    jsContent = jsContent.replace(/from\s*["']\.\/[^"']+["']/g, '');
    
    combinedJs += jsContent + '\n';
  }
  
  // Process all JS files
  for (const jsFile of jsFiles) {
    processJsFile(jsFile);
  }
  
  // Replace all script tags with a single inline script
  htmlContent = htmlContent.replace(/<script[^>]*src="\/[^"]+\.js"[^>]*><\/script>/g, '');
  htmlContent = htmlContent.replace(
    '</body>',
    `<script type="module">${combinedJs}</script></body>`
  );
  
  // Remove modulepreload links
  htmlContent = htmlContent.replace(/<link[^>]*rel="modulepreload"[^>]*>/g, '');
  
  // Escape backticks and ${} in the HTML content for embedding in TypeScript
  const escapedHtml = htmlContent
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');

  const tsContent = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/embed-widget.js
 */

export const WIDGET_HTML = \`${escapedHtml}\`;
`;

  const outputPath = path.join(OUTPUT_DIR, 'widget-html.ts');
  fs.writeFileSync(outputPath, tsContent, 'utf8');
  
  console.log('✅ Self-contained widget HTML generated successfully');
  console.log(`📦 Total size: ${Buffer.byteLength(escapedHtml, 'utf8')} bytes`);
}

embedWidget();

